### ISSUE TITLE
Handle renames & changed paths of ontologies

### ISSUE THREAD

**Issue by meberl** [semiodesk/modom-support#5]
This might become an issue if the repository can be changed manually

**Comment by faubulous** [comment]
The problem is that we do not detect file renames when an ontology file has changed in a Git repository. If 'ex.ttl' is renamed to 'ex2.ttl' and a user has checked out this ontology, all changes are still being comitted to 'ex.ttl'. A new file is created in the repository and the ontologies are forked. This is not the desired behaviour.
